---
- name: Compile userland
  make: 
    chdir: /usr/src
    target: buildworld
    params:
      -j: "{{ ansible_processor_vcpus }}"
  when: base_compile or src_updated
  register: userland_builded
- name: Compile kernel
  make:
    chdir: /usr/src
    target: kernel
    params:
      -j: "{{ ansible_processor_vcpus }}"
  when: kernel_opts or base_compile
- name: Reboot and wait for reboot
  reboot:
    reboot_timeout: 3600
    msg: Reboot initiated Kernel upgrade
  when: kernel_opts or base_compile
- name: Install userland
  make:
    chdir: /usr/src
    target: installworld
    params:
      -j: "{{ ansible_processor_vcpus }}"
  when: base_compile or src_updated
  