---
- name: Compile userland
  make:
    chdir: /usr/src
    target: buildworld
    params:
      "{{ item.key }}: {{ item.value }}"
  with_items:
    - "{{ build_common }}"
  when: (base_compile and src_updated) or (base_compile and src_installed)
  register: userland_builded
- name: combine dict for kernel compilation
  set_fact:
    kernel_options: "{{ build_common + kernel_extra_params }}"
  when:
    - kernel_extra_params is defined
- name: set normal kernel compilation options
  set_fact:
    kernel_options: "{{ build_common }}"
  when:
    - kernel_extra_params is not defined
- name: Compile kernel
  make:
    chdir: /usr/src
    target: buildkernel
    params:
      {"{{ item.key }}" : "{{ item.value }}"}
  with_items:
    - "{{ kernel_options }}"
  when: base_compile or kernel_opts or create_vm
- name: Install kernel
  make:
    chdir: /usr/src
    target: installkernel
    params:
      "{{ item.key }}: {{ item.value }}"
  with_items:
    - "{{ kernel_options }}"
  when: base_compile or kernel_opts
- name: Reboot and wait for reboot
  reboot:
    reboot_timeout: "{{ upgrade_reboot_timeout }}"
    msg: Reboot initiated Kernel upgrade
  when: base_compile or kernel_opts
- name: Install userland
  make:
    chdir: /usr/src
    target: installworld
    params:
      "{{ item.key }}: {{ item.value }}"
  with_items: "{{ build_common }}"
  when: (base_compile and src_updated) or (base_compile and src_installed)
