---
- name: Fetching required components
  get_url:
    dest: "{{ ansible_env.HOME }}/{{ item }}.txz"
    url: ftp://ftp.freebsd.org/pub/FreeBSD/releases/{{ ansible_machine }}/{{ ansible_distribution_release.split("-")[0] }}-{{ ansible_distribution_release.split("-")[1] }}/{{ item }}.txz
  with_items:
    - components
  when: components is defined
- name: Install target components
  shell: tar -C / -xvf {{ item }}.txz
  args:
    chdir: "{{ ansible_env.HOME }}"
  with_items:
    - components
  when: components is defined