---
- name: Fetching required components
  get_url:
    dest: '{{ ansible_env.HOME }}/{{ item }}.txz'
    url: '{{ base_url }}/{{ ansible_machine }}/{{ ansible_distribution_release.split("-")[0] }}-{{ ansible_distribution_release.split("-")[1] }}/{{ item }}.txz'
  with_items: "{{ components }}"
  when: components is defined
- name: Install target components
  unarchive:
      src: "{{ ansible_env.HOME }}/{{ item }}.txz"
      dest: 
      remote_src: yes
  with_items: "{{ components }}"
  when: components is defined
