---
- name: check if ports are installed
  find:
    paths: /usr/ports
    patterns: '*.*'
  register: foundFiles
- name: fetch and extract
  command: portsnap fetch extract
  when: foundFiles.matched > 0
- name: update ports tree
  command: portsnap update
  when: foundFiles.matched > 0

