---
- name: Fetch any new FreeBSD updates
  command: freebsd-update --not-running-from-cron fetch
  register: result_update
  changed_when: "'No updates needed' not in result_update.stdout"
- name: set src updated
  set_fact:
    src_updated: true
  when: "'/usr/src' in result_update.stdout"
- name: set not src updated
  set_fact:
    src_updated: false
  when: "'/usr/src' not in result_update.stdout"
- name: set kernel updated
  set_fact:
    kernel_opts: true
  when: "'/boot/kernel' in result_update.stdout"
- name: set not kernel updated
  set_fact:
    kernel_opts: false
  when: "'/boot/kernel' not in result_update.stdout"
- name: Install FreeBSD updates
  command: freebsd-update --not-running-from-cron install
  when: result_update.changed
  register: result_update_install
- name: Upgrade FreeBSD packages
  shell: pkg upgrade -y
- name: Retrieve all jails
  command: jls -v name path
  register: jail_names
  when: update == "full"
- name: Upgrade FreeBSD packages for jails
  command: pkg -j {{ item.split(" ")[0] }} upgrade -y
  with_items:
    - "{{ jail_names.stdout_lines }}"
  when: update == "full"
- name: Upgrade userland for each jail
  command: freebsd-update -b {{ item.split(" ")[1] }} --not-running-from-cron fetch install
  with_items:
    - "{{ jail_names.stdout_lines }}"
  when: update == "full"
