---
dependency:
  name: galaxy
driver:
  name: openstack
lint:
  name: yamllint
platforms:
  - name: freebsd
    image: FreeBSD-12.0-RELEASE-p2
    flavor: m1.medium
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
